export const PREDEFINED_ITEMS = [
  // DIANTEIRA
  { grupo: 'Dianteira', subgrupo: 'Lubrificação', legenda: 'Lubrificação do eixo da roda dianteira' },
  { grupo: 'Dianteira', subgrupo: 'Lubrificação', legenda: 'Lubrificação do rolamento da roda dianteira lado direito' },
  { grupo: 'Dianteira', subgrupo: 'Lubrificação', legenda: 'Lubrificação do rolamento da roda dianteira lado esquerdo' },
  { grupo: 'Dianteira', subgrupo: 'Lubrificação', legenda: 'Retentor da roda dianteira lado direito' },
  { grupo: 'Dianteira', subgrupo: 'Lubrificação', legenda: 'Retentor da roda dianteira lado esquerdo' },
  { grupo: 'Dianteira', subgrupo: 'Lubrificação', legenda: 'Nível de óleo da bengala' },
  { grupo: 'Dianteira', subgrupo: 'Lubrificação', legenda: 'Cilindro interno da bengala' },
  { grupo: 'Dianteira', subgrupo: 'Lubrificação', legenda: 'Retentor da bengala' },
  { grupo: 'Dianteira', subgrupo: 'Lubrificação', legenda: 'Guarda pó da bengala' },
  { grupo: 'Dianteira', subgrupo: 'Lubrificação', legenda: 'Bucha de cobre da suspensão dianteira' },
  { grupo: 'Dianteira', subgrupo: 'Lubrificação', legenda: 'Lubrificação do conjunto da caixa de direção' },
  { grupo: 'Dianteira', subgrupo: 'Lubrificação', legenda: 'Rolamento inferior da caixa de direção' },
  { grupo: 'Dianteira', subgrupo: 'Lubrificação', legenda: 'Rolamento superior da caixa de direção' },
  
  { grupo: 'Dianteira', subgrupo: 'Desgaste', legenda: 'Conjunto da sapata de freio dianteiro' },
  { grupo: 'Dianteira', subgrupo: 'Desgaste', legenda: 'Pastilha de freio dianteiro' },
  { grupo: 'Dianteira', subgrupo: 'Desgaste', legenda: 'Disco de freio dianteiro' },
  { grupo: 'Dianteira', subgrupo: 'Desgaste', legenda: 'Pneu dianteiro' },

  { grupo: 'Dianteira', subgrupo: 'Elétrico', legenda: 'Interruptor de ignição' },
  { grupo: 'Dianteira', subgrupo: 'Elétrico', legenda: 'Conector do interruptor de ignição' },
  { grupo: 'Dianteira', subgrupo: 'Elétrico', legenda: 'Interruptor esquerdo completo' },
  { grupo: 'Dianteira', subgrupo: 'Elétrico', legenda: 'Conector do interruptor esquerdo completo' },
  { grupo: 'Dianteira', subgrupo: 'Elétrico', legenda: 'Interruptor direito completo' },
  { grupo: 'Dianteira', subgrupo: 'Elétrico', legenda: 'Conector do interruptor direito completo' },
  { grupo: 'Dianteira', subgrupo: 'Elétrico', legenda: 'Painel completo' },
  { grupo: 'Dianteira', subgrupo: 'Elétrico', legenda: 'Conector do painel' },
  { grupo: 'Dianteira', subgrupo: 'Elétrico', legenda: 'Farol completo' },
  { grupo: 'Dianteira', subgrupo: 'Elétrico', legenda: 'Conector do farol' },
  { grupo: 'Dianteira', subgrupo: 'Elétrico', legenda: 'Sinaleiras dianteiras' },
  { grupo: 'Dianteira', subgrupo: 'Elétrico', legenda: 'Conector das sinaleiras dianteiras' },
  { grupo: 'Dianteira', subgrupo: 'Elétrico', legenda: 'Tomada USB' },
  { grupo: 'Dianteira', subgrupo: 'Elétrico', legenda: 'Interruptor de freio dianteiro' },
  { grupo: 'Dianteira', subgrupo: 'Elétrico', legenda: 'Conector do interruptor de freio dianteiro' },
  { grupo: 'Dianteira', subgrupo: 'Elétrico', legenda: 'Sensor de velocidade' },
  { grupo: 'Dianteira', subgrupo: 'Elétrico', legenda: 'Conector do velocímetro sensor de velocidade' },
  { grupo: 'Dianteira', subgrupo: 'Elétrico', legenda: 'Acendedor de cigarro' },

  { grupo: 'Dianteira', subgrupo: 'Chassi', legenda: 'Espaçador da roda dianteira lado direito' },
  { grupo: 'Dianteira', subgrupo: 'Chassi', legenda: 'Espaçador da roda dianteira lado esquerdo' },
  { grupo: 'Dianteira', subgrupo: 'Chassi', legenda: 'Coluna de direção' },
  { grupo: 'Dianteira', subgrupo: 'Chassi', legenda: 'Suporte para celular' },
  { grupo: 'Dianteira', subgrupo: 'Chassi', legenda: 'Espelho de freio dianteiro' },
  { grupo: 'Dianteira', subgrupo: 'Chassi', legenda: 'Pinça de freio dianteiro' },

  // CENTRAL
  { grupo: 'Central', subgrupo: 'Lubrificação', legenda: 'Óleo do motor' },
  { grupo: 'Central', subgrupo: 'Lubrificação', legenda: 'Filtro de óleo do motor' },

  { grupo: 'Central', subgrupo: 'Desgaste', legenda: 'Filtro de ar' },
  { grupo: 'Central', subgrupo: 'Desgaste', legenda: 'Filtro de combustível' },
  { grupo: 'Central', subgrupo: 'Desgaste', legenda: 'Filtro de óleo' },
  { grupo: 'Central', subgrupo: 'Desgaste', legenda: 'Vela de ignição' },

  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Bateria' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Carregador da bateria' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Fusível principal' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Buzina' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Caixa de fusíveis' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Solenoide de partida (relé de partida)' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Bobina de ignição' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'C.D.I' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Conector do C.D.I' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Sensor do cavalete lateral' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Conector do cavalete lateral' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Interruptor de freio traseiro' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Conector do interruptor de freio traseiro' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Regulador retificador de voltagem' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Conector do regulador retificador de voltagem' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Conector do estator com bobinas' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Relé do pisca' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Conector do relé do pisca' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Central de alarme anti-furto' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Conector da central de alarme anti-furto' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Controle remoto' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Conector do sensor de marcha' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Central de ABS' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Conector da central de ABS' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Relé da central de ABS' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'OBD2' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Conector do OBD2' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Bluetooth' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Conector do bluetooth' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Relé de start stop' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Eletroventilador' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Conector do eletroventilador' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Cordão de segurança' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Conector do cordão de segurança' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'E.C.U' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Sensor de pressão absoluta do coletor de admissão (Map)' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Conector do sensor de pressão absoluta do coletor de admissão (Map)' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Sensor de posição do acelerador (TPS )' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Conector sensor de posição do acelerador (TPS )' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Sensor de temperatura do ar (IAT)' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Conector do sensor de temperatura do ar (IAT)' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Sensor de temperatura do óleo do motor (EOT)' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Conector do sensor de temperatura do óleo do motor (EOT)' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Unidade de sensores (IAT, TPS e MAP)' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Conector da unidade de sensores (IAT, TPS e MAP)' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Atuador de marcha lenta' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Conector do atuador de marcha lenta' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Bico Injetor' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Conector do bico injetor' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'T.B.I.' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Coletor de admissão' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Relé principal (EFI)' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Canister' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Válvula de canister' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Conector da válvula do canister' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Sensor de O2 (sonda Lambda)' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Conector do sensor de O2 (sonda lambda)' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Bomba de combustível' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Conector da bomba de combustível' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Relé da bomba de combustível' },
  { grupo: 'Central', subgrupo: 'Elétrico', legenda: 'Conector da válvula termostática' },

  { grupo: 'Central', subgrupo: 'Chassi', legenda: 'Radiador' },

  // TRASEIRA
  { grupo: 'Traseira', subgrupo: 'Lubrificação', legenda: 'Lubrificação do eixo da roda traseira' },
  { grupo: 'Traseira', subgrupo: 'Lubrificação', legenda: 'Lubrificação do rolamento da roda traseira lado direito' },
  { grupo: 'Traseira', subgrupo: 'Lubrificação', legenda: 'Lubrificação do rolamento da roda traseira lado esquerdo' },
  { grupo: 'Traseira', subgrupo: 'Lubrificação', legenda: 'Retentor da roda traseira lado direito' },
  { grupo: 'Traseira', subgrupo: 'Lubrificação', legenda: 'Retentor da roda traseira lado esquerdo' },
  { grupo: 'Traseira', subgrupo: 'Lubrificação', legenda: 'Rolamento do flange da coroa de transmissão' },
  { grupo: 'Traseira', subgrupo: 'Lubrificação', legenda: 'Retentor do flange da coroa de transmissão' },
  { grupo: 'Traseira', subgrupo: 'Lubrificação', legenda: 'Lubrificação do eixo da balança traseira' },
  { grupo: 'Traseira', subgrupo: 'Lubrificação', legenda: 'Lubrificação da bucha/rolamento da balança traseira' },

  { grupo: 'Traseira', subgrupo: 'Desgaste', legenda: 'Conjunto da sapata de freio traseiro' },
  { grupo: 'Traseira', subgrupo: 'Desgaste', legenda: 'Pastilha de freio traseiro' },
  { grupo: 'Traseira', subgrupo: 'Desgaste', legenda: 'Disco de freio traseiro' },
  { grupo: 'Traseira', subgrupo: 'Desgaste', legenda: 'Pneu traseiro' },
  { grupo: 'Traseira', subgrupo: 'Desgaste', legenda: 'Corrente de transmissão' },
  { grupo: 'Traseira', subgrupo: 'Desgaste', legenda: 'Coroa de transmissão' },
  { grupo: 'Traseira', subgrupo: 'Desgaste', legenda: 'Pinhão de transmissão' },
  { grupo: 'Traseira', subgrupo: 'Desgaste', legenda: 'Guia deslizante da corrente de transmissão' },
  { grupo: 'Traseira', subgrupo: 'Desgaste', legenda: 'Absorvedor de choque' },

  { grupo: 'Traseira', subgrupo: 'Elétrico', legenda: 'Lanterna traseira' },
  { grupo: 'Traseira', subgrupo: 'Elétrico', legenda: 'Conector da lanterna traseira' },
  { grupo: 'Traseira', subgrupo: 'Elétrico', legenda: 'Sinaleiras traseiras' },
  { grupo: 'Traseira', subgrupo: 'Elétrico', legenda: 'Conector das sinaleiras traseiras' },
  { grupo: 'Traseira', subgrupo: 'Elétrico', legenda: 'Luz de placa' },
  { grupo: 'Traseira', subgrupo: 'Elétrico', legenda: 'Conector da luz de placa' },

  { grupo: 'Traseira', subgrupo: 'Chassi', legenda: 'Amortecedor traseiro' },
  { grupo: 'Traseira', subgrupo: 'Chassi', legenda: 'Bucha do amortecedor traseiro' },
  { grupo: 'Traseira', subgrupo: 'Chassi', legenda: 'Balança traseira' },
  { grupo: 'Traseira', subgrupo: 'Chassi', legenda: 'Espelho de freio traseiro' },
  { grupo: 'Traseira', subgrupo: 'Chassi', legenda: 'Pinça de freio traseira' },
  { grupo: 'Traseira', subgrupo: 'Chassi', legenda: 'Espaçador da roda traseira lado direito' },
  { grupo: 'Traseira', subgrupo: 'Chassi', legenda: 'Espaçador da roda traseira lado esquerdo' },
];
